In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Student_Performance.csv')
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
data = data.dropna()
data['Extracurricular Activities'] = data['Extracurricular Activities'].map({'Yes': 1, 'No': 0})
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [4]:
train_data = data.sample(frac=0.9,random_state=42)
test_data  = data.drop(train_data.index)
print(train_data.shape,test_data.shape)

(9000, 6) (1000, 6)

In [5]:
X_train = train_data.iloc[:,0:5].to_numpy()
Y_train = train_data.iloc[:,5].to_numpy()
X_test = test_data.iloc[:,0:5].to_numpy()
Y_test = test_data.iloc[:,5].to_numpy()
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(9000, 5) (9000,) (1000, 5) (1000,)

In [6]:
class Linear_Regression:
    def __init__(self,X):
        self.w = np.random.rand(X.shape[1])
        self.b = np.random.rand()
    
    def cost(self,X,Y):
        return np.mean((X.dot(self.w)+self.b-Y)**2)/2
    def gradient(self,X,Y):
        
        dw = np.matmul(X.T,X.dot(self.w)+self.b-Y)/X.shape[0]
        
        db = np.mean((X.dot(self.w)+self.b-Y))
        return dw,db
    def update_weights(self,dw,db,lr):
        self.w = self.w - lr*dw
        self.b = self.b - lr*db
    def z_score(self,X):
        X_mean = X.mean()
        X_std = X.std()
        return (X-X.mean())/X.std(),X_mean,X_std
    def fit(self,X_train,Y_train,lr,epochs):
        X_train_scaled,_,__ = self.z_score(X_train)
        for i in range(epochs):
            dw,db = self.gradient(X_train_scaled,Y_train)
            self.update_weights(dw,db,lr)
            if ((i+1) %100 ==0): print('Epoch:',i+1,'Cost:',self.cost(X_train_scaled,Y_train),"weights:",self.w,"bias:",self.b)
    def predict(self,X_test,X_train):
        _,X_mean,X_std = self.z_score(X_train)
        X_test_scaled = (X_test-X_mean)/X_std
        return X_test_scaled.dot(self.w)+self.b
    def rsme_loss(self,X_test,Y_test):
        Y_pred = self.predict(X_test,X_train)
        return np.sqrt(np.mean((Y_test-Y_pred)**2))

In [10]:
model = Linear_Regression(X_train)
model.fit(X_train,Y_train,0.335,2500)
print('RSME Loss:',model.rsme_loss(X_test,Y_test))

Epoch: 100 Cost: 18.933334861449225 weights: [18.85799951 28.18947566 -2.80056474 -0.31092677  0.12396841] bias: 7.192195926551384
Epoch: 200 Cost: 12.153900595394099 weights: [32.51606559 28.41965232 -5.47018628 -0.46689239  0.19998069] bias: 11.947175114098828
Epoch: 300 Cost: 8.30424383452508 weights: [42.96635411 28.33080447 -7.5521651  -0.267584    0.5463501 ] bias: 15.778910675330724
Epoch: 400 Cost: 6.001894913025488 weights: [50.96464478 28.25503018 -9.1823584   0.16736342  1.01567169] bias: 18.901821371103008
Epoch: 500 Cost: 4.613001416157959 weights: [ 57.09425814  28.19331898 -10.4521797    0.75698142   1.52505676] bias: 21.459026949384423
Epoch: 600 Cost: 3.7665130360701182 weights: [ 61.79827483  28.14309282 -11.43410285   1.44098454   2.02612019] bias: 23.56396985758049
Epoch: 700 Cost: 3.2442148668185657 weights: [ 65.4134633   28.10218591 -12.18581769   2.17488979   2.49249246] bias: 25.306933357654405
Epoch: 800 Cost: 2.9171578743820676 weights: [ 68.19607363  28.06882544 -12.75322928   2.92637587   2.91166741] bias: 26.75972827910623
Epoch: 900 Cost: 2.708742020582598 weights: [ 70.34130372  28.0415682  -13.17286286   3.67242544   3.27961043] bias: 27.979456711302902
Epoch: 1000 Cost: 2.573193785489088 weights: [ 71.99800602  28.01924407 -13.4737897    4.39708948   3.59723551] bias: 29.0115297238474
Epoch: 1100 Cost: 2.4829714858422127 weights: [ 73.27981241  28.00090736 -13.67916441   5.08974622   3.86814095] bias: 29.892078713206352
Epoch: 1200 Cost: 2.421367772007369 weights: [ 74.27355954  27.98579558 -13.80744886   5.74375157   4.09718616] bias: 30.64987665978221
Epoch: 1300 Cost: 2.378148381168901 weights: [ 75.04567743  27.97329492 -13.87338453   6.355398     4.28962419] bias: 31.307865241843327
Epoch: 1400 Cost: 2.346970775550663 weights: [ 75.64703879  27.96291185 -13.88876346   6.92311543   4.45059712] bias: 31.884366287647683
Epoch: 1500 Cost: 2.323849670405928 weights: [ 76.11664424  27.95424967 -13.8630389    7.44686132   4.58486411] bias: 32.394041305833674
Epoch: 1600 Cost: 2.3062404138476453 weights: [ 76.48442562  27.94698956 -13.80380833   7.92765822   4.69667549] bias: 32.848650557340044
Epoch: 1700 Cost: 2.2924883131334406 weights: [ 76.77338067  27.94087511 -13.7171953    8.36724545   4.78973539] bias: 33.25765301532658
Epoch: 1800 Cost: 2.281495553875029 weights: [ 77.00120013  27.93569987 -13.6081512    8.76781918   4.86721585] bias: 33.628680293608966
Epoch: 1900 Cost: 2.2725180743371967 weights: [ 77.18150913  27.93129743 -13.48069366   9.13184043   4.93179824] bias: 33.967910917508284
Epoch: 2000 Cost: 2.2650404567494786 weights: [ 77.32481522  27.92753335 -13.33809503   9.46189507   4.98572724] bias: 34.280365901157374
Epoch: 2100 Cost: 2.2586979460932683 weights: [ 77.43923293  27.92429875 -13.18303133   9.76059341   5.03086819] bias: 34.570142252742905
Epoch: 2200 Cost: 2.253227151472912 weights: [ 77.53103816  27.92150525 -13.01770025  10.03049991   5.06876266] bias: 34.84059755772296
Epoch: 2300 Cost: 2.248434364341689 weights: [ 77.60509257  27.91908086 -12.84391449  10.27408542   5.10067955] bias: 35.094496024758
Epoch: 2400 Cost: 2.2441748173469547 weights: [ 77.66516891  27.91696673 -12.66317595  10.49369624   5.1276603 ] bias: 35.33412418291589
Epoch: 2500 Cost: 2.24033882812145 weights: [ 77.7142005   27.9151146  -12.47673466  10.69153573   5.15055813] bias: 35.561382679024646
RSME Loss: 2.0641153101169247