In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Student_Performance.csv')
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
data = data.dropna()
data['Extracurricular Activities'] = data['Extracurricular Activities'].map({'Yes': 1, 'No': 0})
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [4]:
train_data = data.iloc[0:9000,:]
test_data  = data.iloc[9000:,:]
print(train_data.shape,test_data.shape)

(9000, 6) (1000, 6)

In [5]:
X_train = train_data.iloc[:,0:5].to_numpy()
Y_train = train_data.iloc[:,5].to_numpy()
X_test = test_data.iloc[:,0:5].to_numpy()
Y_test = test_data.iloc[:,5].to_numpy()
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(9000, 5) (9000,) (1000, 5) (1000,)

In [ ]:
class Linear_Regression:
    def __init__(self,X):
        self.w = np.random.rand(X.shape[1])
        self.b = np.random.rand()
    
    def cost(self,X,Y):
        return np.mean((X.dot(self.w)+self.b-Y)**2)/2
    def gradient(self,X,Y):
        
        dw = np.matmul(X.T,X.dot(self.w)+self.b-Y)/X.shape[0]
        
        db = np.mean((X.dot(self.w)+self.b-Y))
        return dw,db
    def update_weights(self,dw,db,lr):
        self.w = self.w - lr*dw
        self.b = self.b - lr*db
    def z_score(self,X):
        X_mean = X.mean()
        X_std = X.std()
        return (X-X.mean())/X.std(),X_mean,X_std
    def fit(self,X_train,Y_train,lr,epochs):
        X_train_scaled,_,__ = self.z_score(X_train)
        for i in range(epochs):
            dw,db = self.gradient(X_train_scaled,Y_train)
            self.update_weights(dw,db,lr)
            if ((i+1) %100 ==0): print('Epoch:',i+1,'Cost:',self.cost(X_train_scaled,Y_train),"weights:",self.w,"bias:",self.b)
    def predict(self,X_test,X_train):
        _,X_mean,X_std = self.z_score(X_train)
        X_test_scaled = (X_test-X_mean)/X_std
        return X_test_scaled.dot(self.w)+self.b
    def rsme_loss(self,X_test,Y_test):
        Y_pred = self.predict(X_test,X_train)
        return np.sqrt(np.mean((Y_test-Y_pred)**2))

In [7]:
model = Linear_Regression(X_train)
model.fit(X_train,Y_train,0.335,2500)
print('RSME Loss:',model.rsme_loss(X_test,Y_test))

Epoch: 100 Cost: 19.13440423241223 weights: [18.45263524 28.20822397 -3.34866326 -0.08001731 -0.03490139] bias: 6.584278236242469
Epoch: 200 Cost: 12.278187074870242 weights: [32.20082292 28.42164799 -6.05017188 -0.18833763  0.08596919] bias: 11.406311796609613
Epoch: 300 Cost: 8.368925686052064 weights: [ 4.27220829e+01  2.83293031e+01 -8.15174606e+00  4.14862397e-02
  4.56623299e-01] bias: 15.288360037277219
Epoch: 400 Cost: 6.031213386309301 weights: [50.77579518 28.25122675 -9.79173128  0.4944892   0.93777498] bias: 18.447970425680953
Epoch: 500 Cost: 4.621856725594178 weights: [ 56.94797988  28.18788887 -11.06420617   1.09283861   1.45143706] bias: 21.031830927983535
Epoch: 600 Cost: 3.763893551659577 weights: [ 61.68412795  28.13651306 -12.04364664   1.77868351   1.95234344] bias: 23.156054521161472
Epoch: 700 Cost: 3.2354433648248544 weights: [ 65.32309549  28.09479564 -12.7892301    2.50942976   2.4160911 ] bias: 24.912901876704236
Epoch: 800 Cost: 2.905320916087009 weights: [ 68.1228932   28.06086571 -13.34796535   3.25421234   2.83139342] bias: 26.375649896454565
Epoch: 900 Cost: 2.69558182035875 weights: [ 70.28017414  28.03321021 -13.75719485   3.99112891   3.19495538] bias: 27.602488791954503
Epoch: 1000 Cost: 2.559656294677703 weights: [ 71.9449744   28.01060919 -14.04659288   4.70507754   3.50812524] bias: 28.63963752139567
Epoch: 1100 Cost: 2.4695389516905077 weights: [ 73.23187601  27.99208139 -14.23975676   5.38607438   3.77474415] bias: 29.523826988280387
Epoch: 1200 Cost: 2.4082581809397694 weights: [ 74.22846975  27.97683887 -14.35547107   6.02795059   3.99979621] bias: 30.28427433375183
Epoch: 1300 Cost: 2.3654336505167044 weights: [ 75.00177799  27.96424966 -14.40871011   6.627348     4.188588  ] bias: 30.944249342174714
Epoch: 1400 Cost: 2.3346458460329016 weights: [ 75.60313431  27.95380719 -14.41143166   7.18294896   4.34627359] bias: 31.522315106250414
Epoch: 1500 Cost: 2.3118722037849677 weights: [ 76.07189449  27.94510548 -14.37320456   7.69488914   4.47760108] bias: 32.03330934949141
Epoch: 1600 Cost: 2.294553060424425 weights: [ 76.43826137  27.93781906 -14.30170461   8.1643127    4.58679797] bias: 32.489119804315656
Epoch: 1700 Cost: 2.2810307566057375 weights: [ 76.72543729  27.93168679 -14.20310611   8.59303784   4.67754057] bias: 32.89929640676708
Epoch: 1800 Cost: 2.2702106431977906 weights: [ 76.95126562  27.9264989  -14.08239088   8.98330751   4.75297191] bias: 33.271534426716734
Epoch: 1900 Cost: 2.2613545997150983 weights: [ 77.12948379  27.92208658 -13.9435922    9.33760567   4.81574536] bias: 33.61205567281287
Epoch: 2000 Cost: 2.2539540737023436 weights: [ 77.27068044  27.91831375 -13.7899874    9.65852364   4.86807958] bias: 33.92590930270955
Epoch: 2100 Cost: 2.2476511223467375 weights: [ 77.38302743  27.91507042 -13.62424992   9.94866463   4.91181632] bias: 34.2172092810425
Epoch: 2200 Cost: 2.2421886378481624 weights: [ 77.47283984  27.91226744 -13.44856961  10.2105771    4.94847611] bias: 34.48932194928491
Epoch: 2300 Cost: 2.237378470570141 weights: [ 77.54500494  27.90983232 -13.2647479   10.44670981   4.9793091 ] bias: 34.74501432744794
Epoch: 2400 Cost: 2.2330806450350935 weights: [ 77.60331093  27.90770591 -13.07427314  10.65938312   5.00534023] bias: 34.98657151297848
Epoch: 2500 Cost: 2.2291895387823373 weights: [ 77.65069914  27.90583979 -12.8783806   10.85077211   5.02740813] bias: 35.2158897590464
RSME Loss: 2.1272822509978124