In [7]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_csv('Student_Performance.csv')
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [9]:
data = data.dropna()
data['Extracurricular Activities'] = data['Extracurricular Activities'].map({'Yes': 1, 'No': 0})
data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [10]:
train_data = data.sample(frac=0.9,random_state=42)
test_data  = data.drop(train_data.index)
print(train_data.shape,test_data.shape)

(9000, 6) (1000, 6)

In [11]:
X_train = train_data.iloc[:,0:5].to_numpy()
Y_train = train_data.iloc[:,5].to_numpy()
X_test = test_data.iloc[:,0:5].to_numpy()
Y_test = test_data.iloc[:,5].to_numpy()
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

(9000, 5) (9000,) (1000, 5) (1000,)

In [62]:
class Linear_Regression:
    def __init__(self,X):
        self.w = np.random.rand(X.shape[1])
        self.b = np.random.rand()
    
    def cost(self,X,Y):
        return np.mean((X.dot(self.w)+self.b-Y)**2)/2
    def gradient(self,X,Y):
        # hi = X.dot(self.w)+self.b-Y
        # print(hi.shape)
        # print(X.T.shape)
        # dw = (X.T)*(X.dot(self.w)+self.b-Y)/X.shape[0]
        dw = np.matmul(X.T,X.dot(self.w)+self.b-Y)/X.shape[0]
        # print(dw.shape)
        db = np.mean((X.dot(self.w)+self.b-Y))
        return dw,db
    def update_weights(self,dw,db,lr):
        self.w = self.w - lr*dw
        self.b = self.b - lr*db
    def z_score(self,X):
        X_mean = X.mean()
        X_std = X.std()
        return (X-X.mean())/X.std(),X_mean,X_std
    def fit(self,X_train,Y_train,lr,epochs):
        X_train_scaled,_,__ = self.z_score(X_train)
        for i in range(epochs):
            dw,db = self.gradient(X_train_scaled,Y_train)
            self.update_weights(dw,db,lr)
            if ((i+1) %100 ==0): print('Epoch:',i+1,'Cost:',self.cost(X_train_scaled,Y_train),"weights:",self.w,"bias:",self.b)
    def predict(self,X_test):
        _,X_mean,X_std = self.z_score(X_test)
        X_test_scaled = (X_test-X_mean)/X_std
        return X_test_scaled.dot(self.w)+self.b
    def rsme_loss(self,X_test,Y_test):
        Y_pred = self.predict(X_test)
        return np.sqrt(np.mean((Y_test-Y_pred)**2))

In [64]:
model = Linear_Regression(X_train)
model.fit(X_train,Y_train,0.335,2000)
print('RSME Loss:',model.rsme_loss(X_test,Y_test))

Epoch: 100 Cost: 19.136520735074154 weights: [18.47207469 28.19561935 -3.33900429 -0.06954227  0.04160901] bias: 6.737881685036166
Epoch: 200 Cost: 12.275187513166586 weights: [32.22015226 28.42247823 -6.01970516 -0.26582728  0.1340408 ] bias: 11.521628934262052
Epoch: 300 Cost: 8.37625517285228 weights: [42.73962712 28.33297408 -8.10839976 -0.09936693  0.49412967] bias: 15.375025009939996
Epoch: 400 Cost: 6.0452560362030505 weights: [50.79085223 28.25671964 -9.74238336  0.30845702  0.97450946] bias: 18.514802060365295
Epoch: 500 Cost: 4.639779759607254 weights: [ 56.96096089  28.19464338 -11.01377738   0.87557121   1.49274114] bias: 21.0852109309988
Epoch: 600 Cost: 3.7837553666776147 weights: [ 61.69595172  28.1441409  -11.99559855   1.54081474   2.00083644] bias: 23.200562668225874
Epoch: 700 Cost: 3.256023028405781 weights: [ 65.33482535  28.10302605 -12.74595457   2.25900768   2.47276525] bias: 24.951810179092046
Epoch: 800 Cost: 2.925907805619913 weights: [ 68.13554019  28.06951016 -13.31107141   2.99727242   2.89630672] bias: 26.411279525721895
Epoch: 900 Cost: 2.7157999405912796 weights: [ 70.29460195  28.04213769 -13.7277201    3.73214623   3.26766291] bias: 27.636468341775558
Epoch: 1000 Cost: 2.579336907077175 weights: [ 71.96186464  28.01972898 -14.02515967   4.44732235   3.58794191] bias: 28.67309060905515
Epoch: 1100 Cost: 2.4886349668617704 weights: [ 73.25172725  28.00133093 -14.22668767   5.1318906    3.86089993] bias: 29.55750905633637
Epoch: 1200 Cost: 2.4267894431380808 weights: [ 74.25161419  27.98617534 -14.3508744    5.77897353   4.09152378] bias: 30.318672774903675
Epoch: 1300 Cost: 2.3834533431567464 weights: [ 75.02840577  27.97364404 -14.41254319   6.38467393   4.28516871] bias: 30.979657026976895
Epoch: 1400 Cost: 2.352220650887981 weights: [ 75.63331976  27.96324011 -14.42354756   6.94726688   4.44705829] bias: 31.55888453615173
Epoch: 1500 Cost: 2.3290711079143125 weights: [ 76.10562119  27.9545643  -14.39338666   7.46658291   4.58201634] bias: 32.071092632504104
Epoch: 1600 Cost: 2.311441443719791 weights: [ 76.47544444  27.9472958  -14.32969191   7.94353991   4.69434426] bias: 32.52809821022354
Epoch: 1700 Cost: 2.2976676126167983 weights: [ 76.76594243  27.94117674 -14.23861176   8.37979056   4.78778638] bias: 32.93940223042459
Epoch: 1800 Cost: 2.2866475980053758 weights: [ 76.99492471  27.93599955 -14.12511559   8.77745893   4.86554618] bias: 33.31266715077489
Epoch: 1900 Cost: 2.2776359164133373 weights: [ 77.17610738  27.93159697 -13.99323385   9.13894572   4.93032962] bias: 33.65409389036102
Epoch: 2000 Cost: 2.270117158652836 weights: [ 77.32006756  27.92783394 -13.84624776   9.4667861    4.98440045] bias: 33.968719476273826
RSME Loss: 2.081966925056152